version: '3.3'
services:
    web:
        ports:
            - 80
        env_file: .env
        build: .
    mydb:
        ports:
            - '3306'
        volumes:
            - ./sql/set5:/docker-entrypoint-initdb.d
            - persondb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        image: mysql
    adminer:
        ports:
            - '8080'
        image: adminer
volumes:
  persondb: